apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: certmanager
  namespace: cert-manager  
spec:
  releaseName: certmanager
  chart:
    repository: https://charts.jetstack.io
    version: v0.9.1
    name: cert-manager
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rancher
  namespace: rancher
spec:
  chart:
    repository: https://releases.rancher.com/server-charts/stable
    version: v2.2.8
    name: rancher
  values:
    hostname: rancher.my.org