apiVersion: v1
kind: Namespace
metadata:
  name: rancher
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: certmanager
  labels:
    certmanager.k8s.io/disable-validation: "true"